// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef AspEditUI_h
#define AspEditUI_h
#include <fltk/Window.h>
#include <fltk/Choice.h>
#include <fltk/Button.h>
#include <fltk/Group.h>
#include <fltk/RadioButton.h>
#include <fltk/Browser.h>

class AspEditUI  {
public:
	AspEditUI();
	fltk::Window *window;
		fltk::Choice *cbSys;
		fltk::Button *bNew;
		fltk::Button *bEdit;
		fltk::Button *bCopy;
		fltk::Browser *dgAsp;
};
#endif
