// generated by Fast Light User Interface Designer (fluid) version 2.1000

#include "AspEditUI.h"

AspEditUI::AspEditUI() {
	fltk::Window* w;
	 {fltk::Window* o = window = new fltk::Window(920, 665, "\320\232\320\276\320\275\321\201\321\202\321\200\321\203\320\272\321\202\320\
\276\321\200 \320\260\321\201\320\277\320\265\320\272\321\202\320\276\320\262");
		w = o;
		o->shortcut(0xff1b);
		o->user_data((void*)(this));
		o->begin();
		 {fltk::Choice* o = cbSys = new fltk::Choice(0, 5, 155, 25);
		}
		bNew = new fltk::Button(165, 5, 115, 25, "\320\241\320\276\320\267\320\264\320\260\321\202\321\214...");
		bEdit = new fltk::Button(285, 5, 115, 25, "\320\240\320\265\320\264\320\260\320\272\321\202\320\270\321\200\320\276\320\
\262\320\260\321\202\321\214");
		bCopy = new fltk::Button(435, 5, 115, 25, "\320\232\320\276\320\277\320\270\321\200\320\276\320\262\320\260\321\202\321\
\214");
		 {fltk::Group* o = new fltk::Group(560, 5, 360, 25);
			o->box(fltk::BORDER_BOX);
			o->begin();
			new fltk::RadioButton(5, 5, 50, 15, "rad*");
			new fltk::RadioButton(80, 5, 50, 15, "tr*");
			new fltk::RadioButton(155, 5, 50, 15, "pr*");
			new fltk::RadioButton(230, 5, 50, 15, "dir*");
			new fltk::RadioButton(305, 5, 50, 15, "pf*");
			o->end();
		}
		 {fltk::Browser* o = dgAsp = new fltk::Browser(0, 35, 920, 630);
			fltk::Group::current()->resizable(o);
			fltk::Group::current()->resizable(o);
		}
		o->end();
	}
}
