// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef ChronoUI_h
#define ChronoUI_h
#include <fltk/Window.h>
#include <fltk/TextDisplay.h>
#include <fltk/Group.h>
#include <fltk/RepeatButton.h>
#include <fltk/Input.h>

class ChronoUI  {
public:
	fltk::Window* make_window();
	fltk::Window *window;

class TimeTuner  {
public:
	long id;
	TimeTuner(int x, int y, long id_, const char* label_);
};
};
#endif
