// generated by Fast Light User Interface Designer (fluid) version 2.1000

#include "ChronoUI.h"

fltk::Window* ChronoUI::make_window() {
	fltk::Window* w;
	 {fltk::Window* o = window = new fltk::Window(165, 195, "\320\245\321\200\320\276\320\275\320\276\321\201");
		w = o;
		o->shortcut(0xff1b);
		o->user_data((void*)(this));
		o->begin();
		 {fltk::TextDisplay* o = new fltk::TextDisplay(41, 0, 106, 20, "\320\240\320\260\320\264\320\270\320\272\321\201");
			o->labeltype(fltk::EMBOSSED_LABEL);
			o->labelsize(10);
			o->textsize(10);
		}
		o->end();
		o->set_non_modal();
		o->resizable(o);
	}
	return  w;
}

ChronoUI::TimeTuner::TimeTuner(int x, int y, long id_, const char* label_) {
	fltk::Group* w;
	 {fltk::Group* o = new fltk::Group(0, 0, 130, 20);
		w = o;
		o->shortcut(0xff1b);
		o->user_data((void*)(this));
		o->begin();
		new fltk::RepeatButton(37, 3, 18, 15, "@s5@<");
		new fltk::RepeatButton(55, 3, 18, 15, "@s5@>");
		 {fltk::Input* o = new fltk::Input(75, 1, 33, 18);
			o->labelsize(10);
			o->textsize(10);
		}
		new fltk::RepeatButton(110, 3, 18, 8, "@s4@2<");
		new fltk::RepeatButton(110, 10, 18, 8, "@s4@8<");
		o->end();
		o->resizable(o);
	}
	id=id_;
	w->copy_label(label_);
}
