// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef LibUI_h
#define LibUI_h
#include <fltk/Window.h>
#include <fltk/Group.h>
#include <fltk/Browser.h>

class LibUI  {
public:
	LibUI();
	fltk::Window *window;
			fltk::Browser *lbTheme;
			fltk::Browser *lbTopic;
		fltk::Browser *lwLib;
};
#endif
