// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef MainWindow_h
#define MainWindow_h
#include <fltk/Window.h>
#include <fltk/ask.h>
#include <stdio.h>
#include <fltk/MenuBar.h>
#include <fltk/ItemGroup.h>
#include <fltk/Item.h>
#include <fltk/Browser.h>
#include <fltk/ValueSlider.h>
#include <fltk/Dial.h>
#include <fltk/Widget.h>

class MainWindow  {
public:
	MainWindow();
	fltk::Window *window;
private:
				inline void cb_New_i(fltk::Item*, void*);
				static void cb_New(fltk::Item*, void*);
				inline void cb_Quit_i(fltk::Item*, void*);
				static void cb_Quit(fltk::Item*, void*);
				inline void cb_New1_i(fltk::Item*, void*);
				static void cb_New1(fltk::Item*, void*);
	void fillBrowser(fltk::Browser *o, int count);
};
#endif
