// generated by Fast Light User Interface Designer (fluid) version 2.1000

#include "MainWindow.h"

inline void MainWindow::cb_New_i(fltk::Item*, void*) {
	fltk::message("How are you, pals?");
}
void MainWindow::cb_New(fltk::Item* o, void* v) {
	((MainWindow*)(o->parent()->parent()->parent()->user_data()))->cb_New_i(o,v);
}

inline void MainWindow::cb_Quit_i(fltk::Item*, void*) {
	window->hide();
}
void MainWindow::cb_Quit(fltk::Item* o, void* v) {
	((MainWindow*)(o->parent()->parent()->parent()->user_data()))->cb_Quit_i(o,v);
}

inline void MainWindow::cb_New1_i(fltk::Item*, void*) {
	fltk::message("Ephemeris");
}
void MainWindow::cb_New1(fltk::Item* o, void* v) {
	((MainWindow*)(o->parent()->parent()->parent()->user_data()))->cb_New1_i(o,v);
}

#include <fltk/SharedImage.h>

MainWindow::MainWindow() {
	fltk::Window* w;
	 {fltk::Window* o = window = new fltk::Window(725, 445, "Scythian");
		w = o;
		o->color((fltk::Color)0x8cb0e000);
		o->shortcut(0xff1b);
		o->user_data((void*)(this));
		o->begin();
		 {fltk::MenuBar* o = new fltk::MenuBar(0, 0, 725, 20);
			o->shortcut(0xffe9);
			o->align(fltk::ALIGN_TOP|fltk::ALIGN_BOTTOM);
			o->begin();
			 {fltk::ItemGroup* o = new fltk::ItemGroup("File");
				o->begin();
				 {fltk::Item* o = new fltk::Item("New");
					o->callback((fltk::Callback*)cb_New);
				}
				new fltk::Item("Open");
				 {fltk::Item* o = new fltk::Item("Quit");
					o->callback((fltk::Callback*)cb_Quit);
				}
				o->end();
			}
			 {fltk::ItemGroup* o = new fltk::ItemGroup("Ephemeris");
				o->begin();
				 {fltk::Item* o = new fltk::Item("New");
					o->callback((fltk::Callback*)cb_New1);
				}
				new fltk::Item("Open");
				new fltk::Item("Quit");
				o->end();
			}
			o->end();
		}
		 {fltk::Browser* o = new fltk::Browser(545, 20, 180, 217);
			o->set_vertical();
			o->align(fltk::ALIGN_TOP|fltk::ALIGN_BOTTOM|fltk::ALIGN_RIGHT);
			o->begin();
			new fltk::Item("Planet0");
			 {fltk::Item* o = new fltk::Item("Planet1");
				o->align(fltk::ALIGN_CENTER);
			}
			new fltk::ValueSlider(2, 34, 176, 15);
			new fltk::Dial(2, 49, 176, 64);
			o->end();
		}
		 {fltk::Browser* o = new fltk::Browser(545, 237, 180, 208);
			o->set_vertical();
			o->align(fltk::ALIGN_TOP|fltk::ALIGN_BOTTOM|fltk::ALIGN_RIGHT);
			o->begin();
			new fltk::Item("Planet0");
			 {fltk::Item* o = new fltk::Item("Planet1");
				o->align(fltk::ALIGN_CENTER);
			}
			new fltk::ValueSlider(2, 34, 176, 15);
			o->end();
		}
		 {fltk::Browser* o = new fltk::Browser(0, 20, 545, 205);
			const int widths[]={100,50,75};
			const char* lbl[]={"1st", "2nd", "3rd"};
			o->column_widths(widths);
			o->column_labels(lbl);
			fillBrowser(o,30);
		}
		 {fltk::Widget* o = new fltk::Widget(5, 240, 535, 50);
			o->image(fltk::SharedImage::get("planet12.gif"));
		}
		o->end();
		o->resizable(o);
	}
}

void MainWindow::fillBrowser(fltk::Browser *o, int count) {
	char buf[20];
	o->begin();
	for(int i=0; i<count; i++){
		sprintf(buf,"%02d\t%d",i,i);
		(new fltk::Item(0))->copy_label(buf);
	}
	o->end();
}
