// generated by Fast Light User Interface Designer (fluid) version 2.1000

#ifndef fMain_h
#define fMain_h
#include "fltk/Browser.h"
#include "fltk/IntInput.h"

class MyBrowser : public fltk::Browser  {
	virtual int handle(int event);
public:
	MyBrowser(int x, int y, int w, int h, const char *l);
};
#include <fltk/Window.h>
#include <fltk/Group.h>
extern void cb_unselect(MyBrowser*, void*);
extern MyBrowser* lbSelected;
extern void cb_select(MyBrowser*, void*);
extern MyBrowser* lbAvailable;
#include <fltk/IntInput.h>
extern fltk::IntInput* txtYear;
#include <fltk/Button.h>
extern fltk::Button* bSetYear;
#include <fltk/PopupMenu.h>
extern fltk::PopupMenu* pbLang;
extern void cb_do_demo(fltk::Button*, void*);
extern void cb_imei_changed(fltk::IntInput*, void*);
extern fltk::IntInput* txtImei;
extern void cb_do_imei(fltk::Button*, void*);
extern fltk::Button* bImei;
extern fltk::Button* bImeiLogger;
extern fltk::IntInput* txtTimeOffset;
#include <fltk/FloatInput.h>
extern fltk::FloatInput* txtTimeDelta;
extern void cb_do_timebomb(fltk::Button*, void*);
#include <fltk/CheckButton.h>
extern fltk::CheckButton* ckDebug;
extern fltk::CheckButton* ckMessjar;
extern fltk::CheckButton* ckKzip;
#include <fltk/Output.h>
extern fltk::Output* lbLoclist;
extern void cb_load_loclist(fltk::Button*, void*);
extern void cb_save_loclist(fltk::Button*, void*);
extern void cb_clear_loclist(fltk::Button*, void*);
#include <fltk/RadioButton.h>
extern void cb_sort(fltk::RadioButton*, void*);
extern void cb_do_geo(fltk::Button*, void*);
extern fltk::Output* lbSize;
fltk::Window* make_window();
#endif
