// generated by Fast Light User Interface Designer (fluid) version 2.1000

#include "fMain.h"
#include <stdio.h>
#include <fltk/run.h>
#include <fltk/filename.h>
#include <fltk/ask.h>
#include <time.h>
#include <string>
#include <vector>
#include <algorithm>
using namespace std;

fltk::Window *wnd=(fltk::Window *)0;
/*
fltk::Input *txtYear=(fltk::Input *)0;
fltk::Input *txtImei=(fltk::Input *)0;
fltk::Input *txtTimebomb=(fltk::Input *)0;
fltk::CheckButton *ckDebug=(fltk::CheckButton *)0;
fltk::CheckButton *ckKzip=(fltk::CheckButton *)0;
fltk::Output *lbSize=(fltk::Output *)0;
fltk::Browser *lbSelected=(fltk::Browser *)0;
fltk::Browser *lbAvailable=(fltk::Browser *)0;
 */
char path[256];
int year=0;
bool sortbystate=false;

struct City{
	string city, state, datapath;
};

typedef vector<City> LocRec;

LocRec selected, avail;

void refill_all();
void do_sort();
void get_city_list(LocRec &v);

void refresh_lbsize() {
	int sz=selected.size();
	if(!sz){
		lbSize->copy_label("");
	}
	else{
		float locsize=(5100+(sz)*8300/2.25)/1024;
		char lbl[100];
		sprintf(lbl, "Cities = %d,   file size ~ %.2f kb",sz, locsize);
		lbSize->text(lbl);
	}
}

void move_record(LocRec &src, LocRec &dest, int index){
	if((index>=0) && (index<src.size())){
		dest.push_back(src[index]);
		LocRec::iterator iter=src.begin()+index;
		src.erase(iter);
		refresh_lbsize();
	}
}

void cb_sort(fltk::RadioButton *chk, void*) {
	printf("%s\n", chk->label());
	sortbystate=(int)chk->user_data()==1;
	do_sort();
}

void cb_select(MyBrowser *lst, void*) {
	move_record(avail, selected, lst->value());
	refill_all();
}

void cb_unselect(MyBrowser *lst, void*) {
	move_record(selected, avail, lst->value());
	refill_all();
	do_sort();
}

void set_year(const char *str) {
	static char title[80];
	int tmp;
	if(sscanf(str, "%4d", &tmp)==1){
		snprintf(title, 80, "RelGui - %s", str);
		year=tmp;
		wnd->label(title);
	    get_city_list(avail);
		refill_all();
	}
	else{
		fltk::alert("Invalid year - %s", str);
	}
}

void refill_list(fltk::Browser *lst, LocRec &v) {
	char item_name[300];
	lst->clear();
	for(int i=0; i<v.size(); i++){
		if(sortbystate){
			sprintf(item_name, "%s, %s", v[i].state.c_str(), v[i].city.c_str());
		}
		else{
			sprintf(item_name, "%s, %s", v[i].city.c_str(), v[i].state.c_str());
		}
		lst->add(item_name);
	}
}

void refill_all() {
	refill_list(lbSelected, selected);
	refill_list(lbAvailable, avail);
	do_sort();
}


int ini_filter(const struct dirent *de) {
	return (int)strstr(de->d_name, ".ini");
}

void get_city_list(LocRec &v) {
	v.clear();
	struct dirent **namelist;
	char cur_txt[1000];
	char ini[100];
	City rec;
	int n = fltk::filename_list(".", &namelist, 0);
	if (!n)
		perror("scandir");
	else {
		for(int i=0; i<n; i++) {
			strcpy(cur_txt, namelist[i]->d_name);
			free(namelist[i]);
			if(!fltk::filename_match(cur_txt, "*.ini")){
				continue;
			}
			strcpy(ini, cur_txt);
			*(fltk::filename_ext(ini))=0;
			strcpy(fltk::filename_ext(cur_txt), ".txt");
			if(!fltk::filename_exist(cur_txt)){
				printf("No region: %s\n", cur_txt);
				continue;
			}
			FILE *intxt=fopen(cur_txt, "r");
			if(!intxt){
				perror("txt open");
				continue;
			}
			int ii=0;
			char *city, *state;
			while(fgets(cur_txt, 1000, intxt)){
				if(strstr(cur_txt, "#"))
					continue;
				*(strchrnul(cur_txt, '\r'))=0;
				*(strchrnul(cur_txt, '\n'))=0;
				state=rindex(cur_txt, '|')+1;
				*(index(cur_txt, '|'))=0;
				city=cur_txt;
				char* ind=index(cur_txt, '!');
				if(ind){
					city=ind+1;
				}
				ind=index(state, '$');
				if(ind){
					state=ind+1;
				}
//		printf("\nC: %s\tS: %s", city, state);
				char dpath[1000];
				sprintf(dpath, "%04d/%s/Data%02d.dat", year, ini, ii++);
				if(fltk::filename_exist(dpath)){
					rec.city=city; rec.state=state; rec.datapath=dpath;
					v.push_back(rec);
				}
				else{
					printf("No datafile %s\n", dpath);
				}
			}
		}
		free(namelist);
	}
}

bool comparator(const City &lhs, const City &rhs){
	if(sortbystate){
		return strcmp(lhs.state.c_str(), rhs.state.c_str())<0;
	}
	else{
		return strcmp(lhs.city.c_str(), rhs.city.c_str())<0;
	}
}

void do_sort(){
	sort(avail.begin(), avail.end(), comparator);
	refill_list(lbAvailable, avail);
}
// Callbacks
static void cb_SetYear(fltk::Button*, void*) {
	set_year(txtYear->value());
}

void cb_do_imei(fltk::Button*, void* udata){
	
}

void cb_do_timebomb(fltk::Button*, void*){
	
}

/*
fltk::Window* make_window() {
	fltk::Window* w;
	{fltk::Window* o = new fltk::Window(10, 10, 950, 540, "RelGui");
	 w = o;
	 o->shortcut(0xff1b);
	 o->begin();
	 {fltk::Group* o = new fltk::Group(5, 5, 200, 530);
	  o->set_vertical();
	  o->box(fltk::THIN_DOWN_BOX);
	  o->begin();
	  txtYear = new fltk::Input(5, 5, 85, 20);
	  {fltk::Button* o = new fltk::Button(95, 5, 95, 20, "Set year");
	   o->callback((fltk::Callback*)cb_SetYear);
	  }
	  txtImei = new fltk::Input(5, 75, 190, 25);
	  new fltk::Button(5, 105, 85, 25, "IMEI");
	  new fltk::Button(110, 105, 85, 25, "IMEI logger");
	  {fltk::Input* o = txtTimebomb = new fltk::Input(5, 140, 190, 25);
	   o->text("0");
	  }
	  new fltk::Button(35, 170, 120, 25, "Time bomb");
	  ckDebug = new fltk::CheckButton(10, 195, 95, 25, "Debug");
	  ckKzip = new fltk::CheckButton(110, 195, 65, 25, "kzip");
	  {fltk::Group* o = new fltk::Group(5, 345, 190, 35, "Sort by:");
	   o->box(fltk::THIN_DOWN_BOX);
	   o->begin();
	   {fltk::RadioButton* o = new fltk::RadioButton(5, 5, 80, 25, "City");
		o->set_flag(fltk::STATE);
		o->callback((fltk::Callback*)cb_Sort);
	   }
	   {fltk::RadioButton* o = new fltk::RadioButton(105, 5, 80, 25, "State");
		o->callback((fltk::Callback*)cb_Sort);
		o->user_data((void*)1);
	   }
	   o->end();
	  }
	  o->end();
	 }
	 lbSize = new fltk::Output(10, 230, 190, 25);
	 new fltk::Button(10, 505, 185, 25, "Generate Geo");
	 {fltk::Group* o = new fltk::Group(210, 5, 735, 530);
	  o->box(fltk::THIN_DOWN_BOX);
	  o->buttonbox(fltk::NO_BOX);
	  o->begin();
	  {fltk::Browser* o = lbSelected = new fltk::Browser(5, 20, 350, 505, "Selected");
	   o->set_vertical();
	   o->callback((fltk::Callback*)cb_Unselect);
	  }
	  {fltk::Browser* o = lbAvailable =new fltk::Browser(360, 20, 370, 505, "Available");
	   o->set_vertical();
	   o->callback((fltk::Callback*)cb_Select);
	  }
	  o->end();
	 }
	 o->end();
	 o->resizable(o);
	}
	return  w;
}
 */

int main(int argc, char** argv) {
	char ystr[5];
	time_t t;
	struct tm *tmp;
	
	t = time(NULL);
	tmp = localtime(&t);
	year=tmp->tm_year+1900;
	sprintf(ystr, "%04d", year);
	
	strcpy(path, argv[0]);
	printf("argv[0] is: %s\n", path);
	char *pos=strrchr(path, '\\');
	if(!pos){
		pos=strrchr(path, '/');
	}
	if(pos){
		*(pos+1)=0;
	}
	else{
		path[0]=0;
	}
	strcat(path, "../data/archive/");
	chdir(path);
	printf("Current directory is: %s\n", path);
	wnd=make_window();
	txtYear->text(ystr);
	cb_SetYear(0, 0);
	wnd->x(50);	wnd->y(50);
	wnd->show();
	return fltk::run();
}

