##Baltic:LVA,LTU,EST,BLR
@ Latvia, Riga
Riga
Liepaja
Daugavpils
@ Estonia, Tallinn
Tallinn
Tartu
Narva
@ Lithuania, Vilnius
Vilnius
Klaipeda
Panevezys
Siauliai
Druskininkai
@ Belarus, Minsk
Minsk
Gomel'!Gomel
Mogilev
Vitebsk
Grodno
Brest
@ Moldova, Chisinau
Chisinau
Bendery
Balti
Tiraspol'!Tiraspol
Kagul
