##Mexico: MEX
@ Mexico, Tijuana BCN
Tijuana
@ Mexico, Chihuahua CHI
Ciudad Juarez
Culiacan
@ Mexico, Mexico City
Mexico
Guadalajara
Monterrey
Nuevo Laredo
Tampico
Acapulco
Merida
Villahermosa
@ Mexico, Hermosillo SON
Ciudad Obregón
@ Cuba, Havana
Guantanamo
Santa Clara
@ Bahamas (USA), Nassau
Nassau
@ Jamaica, Kingston
Kingston
@ Haiti, Port-au-Prince
Port-au-Prince
@ Dominican Republic, Santo Domingo
Santo Domingo
@ Puerto Rico, San Juan
San Juan
@ Martinique (FRA), Fort-de-France
Fort-de-France
@ Grenada, Saint George's
Saint George's
@ Barbados, Bridgetown
Bridgetown
@ Guatemala, Guatemala
Guatemala
@ El Salvador, San Salvador
San Salvador
@ Honduras, Tegucigalpa
Tegucigalpa
@ Nicaragua, Managua
Managua
@ Costa Rica, San Jose
San Jose
@ Panama, Panama City
Panama
