##Caucasus:
@ Georgia, Tbilisi
Tbilisi
Batumi
Kutaisi
Rustavi
Sukhumi
@ Armenia, Yerevan
Yerevan
Leninakan!Leninakan
Kadzaran!Kadzaran
@ Azerbaijan, Baku
Stepanakert
Kirovabad!Gandzha
Dzhalilabad
Zardob