##Eastern Europe:LVA,LTU,EST,POL,CZE,HUN,ROU,BGR
@ Latvia, Riga
@ Estonia, Tallinn
@ Lithuania, Vilnius
@ Poland, Warsaw
Poznan
Wroclaw
Krakow
@ Czechoslovakia, Prague
#Czech Republic
Brno
Breclav
#@ Slovakia, Bratislava
@ Hungary, Budapest
@ Romania, Bucharest
@ Bulgaria, Sofia
