##Kazakhstan: KAZ
@ Kazakhstan, Aqtobe (Aktyubinsk)
Akt'ubinsk!Aktyubinsk
Ural'sk!Uralsk
Gurjev
Shevchenko
Kandagatj
@ Kazakhstan, Astana
Astana
Kustanai
Kzyl-Orda
Chimkent
Dzjambul
Dzhezkazgan
Karaganda
Koktjetav
Pavlodar
Semipalatinsk
Ust-Kamenogorsk
Taldyqorghan
Almaty
