##Near East:EGY,
@ United Arab Emirates, Dubai
Dubai
@ Saudi Arabia, Riyadh
Riyadh
Jiddah
Medina
@ Yemen, Sana´a
Sanaw
Aden
@ Ethiopia, Addis Ababa
Addis Ababa
@ Israel, Jerusalem
Jerusalem
@ Syria, Damascus
Damascus
@ Iraq, Baghdad
Baghdad
@ Iran, Tehran
Tehran
@ Kuwait, Kuwait City
Al-Kuwayt
