##Pacific Ocean:JAP,PHL,VNM,SGP,IDN,AUS,NZL,THA,PNG
@ Japan, Tokyo
Tokyo
Kioto!Kyoto
@ Philippines, Manila
Manila
@ Vietnam, Hanoi
Ha-Noi!Hanoi
@ Singapore, Singapore
Singapore
@ Indonesia, Jakarta
Jakarta
@ Australia - New South Wales, Sydney
Sydney
@ Australia - Victoria, Melbourne
Melbourne
@ Australia - West, Perth
Perth
@ New Zealand, Wellington
Wellington
@ Thailand, Bangkok
Bangkok
@ Papua New Guinea, Port Moresby
Port Moresby