##Russia: RUS
@ Russia, Moscow
Moscow
Armavir
Astrakhan
Belgorod
Bryansk
Chelyabinsk
Cherepovets
Chita
Irkutsk
Jaroslavl'!Yaroslavl
Kaliningrad
Kaluga
Kazan'!Kazan
Khabarovsk
Krasnodar
Krasnoyarsk
Kursk
Nizhny Novgorod
Novosibirsk
Omsk
Orel
Orenburg
Perm'!Perm
Pskov
Rostov-Na-Donu
Samara
Saransk
Saratov
Smolensk
Sochi
St Peterburg!Sankt Petersburg
Tambov
Tobol'sk!Tobolsk
Tver'!Tver
Tyumen'!Tyumen
Ufa
Vladimir
Vladivostok
Volgograd
Voronezh
Yekaterinburg!Ekaterinburg
