##Stans: UZB,TKM,KGZ,TJK
@ Uzbekistan, Tashkent
Tashkent
Nukus
Navoi
Buchara
Samarkand
Fergana
Termez
@ Turkmenistan, Ashgabat
Ashgabat
Tashauz
Chardzhou
Nebit-Dag!Nebitdag
Mary
Kushka
@ Kyrgyzstan, Bishkek
Bishkek
Osh
Przhevalsk
Talas
Naryn
@ Tajikistan, Dushanbe
Dushanbe
Qurghonteppa
Uroteppa
Khorugh
Murgab

