##test:misc
@ Switzerland, Bern
Lugano
Zurich
Geneva
Lausanne
Basel
@ Austria, Vienna
Salzburg
Graz
Linz
Braunau am Inn
Bregenz
Klagenfurt
@ Germany, Berlin
Berchtesgaden
Bremen
Hannover
Essen
Bonn
Frankfurt am Main
Stuttgart
Regensburg
Leipzig
Rostock
Magdeburg
Dusseldorf
Dresden
@ Poland, Warsaw
Gdansk
Szczecin
Lodz
Bialystok
Lublin
Katowice
@ Turkey, Ankara
Izmir
Ankara
Marmaris
Fethiye
Alanya
Mersin
Adana
@ France, Paris
Perpignan
Lourdes
La Rochelle
St Gilles Croix de Vie
Angers
Nice
Grenoble
Mulhouse
Limoges
Rheims
Lille
Havre
@ Austria, Vienna
Eisentadt
@ France, Paris
Montpellier
