##Ukraine:UKR
@ Ukraine, Kiev
Kiev
Berdyansk
Cherkassy
Chernigov
Chernovtsy
Dnepropetrovsk
Donetsk
Izmail
Ivano-Frankovsk
Kerch
Kharkov
Kherson
Khmel'nitskiy!Khmelnitsky
Kirovograd
Krivoy Rog!Krivoi Rog
Kovel'
Lugansk
Lutsk
L'vov!Lvov
Nikolayev!Nikolaev
Odessa
Poltava
Rovno
Simferopol'!Simferopol
Sumy
Ternopol'!Ternopol
Uman'
Uzgorod!Uzhgorod
Vinnitsa
Zaporozje
Zhitomir
Yalta
Jaremca
