##Ukraine:UKR
@ Ukraine, Kiev
Cherkassy
Chernigov
Chernovtsy
Dnepropetrovsk
Donetsk
Ivano-Frankovsk
Kharkov
Kherson
Khmel'nitskiy
Kirovograd
Krivoy Rog
Lugansk
Lutsk
L'vov
Nikolayev
Odessa
Poltava
Rovno
Simferopol'
Sumy
Ternopol'
Uzhgorod
Vinnitsa
Zaporozje
Zhitomir
Yalta
