##Western Europe:GBR,IRL,FRA,ESP,PRT,GIB,LUX
@ England, London
London
@ Scotland
Edinburgh
@ Ireland, Dublin
Dublin
@ France, Paris
Paris
Bordeaux
Lyon
Marseille
@ Spain, Madrid
Barcelona
Madrid
@ Portugal, Lisbon
Lisbon
@ Gibraltar, Gibraltar
Gibraltar
@ Luxembourg, Luxembourg
Luxembourg
@ England, London
Halifax